-- MySQL Script generated by MySQL Workbench
-- Fri Apr  1 16:50:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quest_lovers
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `quest_lovers` ;

-- -----------------------------------------------------
-- Schema quest_lovers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quest_lovers` DEFAULT CHARACTER SET utf8 ;
USE `quest_lovers` ;

-- -----------------------------------------------------
-- Table `quest_lovers`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quest_lovers`.`user` ;

CREATE TABLE IF NOT EXISTS `quest_lovers`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(13) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quest_lovers`.`type_of_game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quest_lovers`.`type_of_game` ;

CREATE TABLE IF NOT EXISTS `quest_lovers`.`type_of_game` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quest_lovers`.`quest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quest_lovers`.`quest` ;

CREATE TABLE IF NOT EXISTS `quest_lovers`.`quest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `type_of_game_id` INT NOT NULL,
  `min_number_of_players` INT NOT NULL,
  `max_number_of_players` INT NULL,
  `age_limit` INT NOT NULL,
  `age_limit_with_accompaniment` INT NULL,
  `level_of_difficulty` INT NOT NULL,
  `level_of_fear` INT NOT NULL,
  `rating` FLOAT NULL,
  `duration` INT NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(13) NULL,
  `email` VARCHAR(255) NULL,
  `annotation` VARCHAR(200) NULL,
  `full_desc` VARCHAR(800) NOT NULL,
  `specifics` VARCHAR(600) NULL,
  `schedule` JSON NOT NULL,
  `number_of_review` INT NOT NULL,
  `path_to_images` VARCHAR(255) NOT NULL,
  `number_of_images` INT NOT NULL,
  PRIMARY KEY (`id`, `type_of_game_id`),
  INDEX `fk_quest_type_of_game1_idx` (`type_of_game_id` ASC),
  CONSTRAINT `fk_quest_type_of_game1`
    FOREIGN KEY (`type_of_game_id`)
    REFERENCES `quest_lovers`.`type_of_game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quest_lovers`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quest_lovers`.`booking` ;

CREATE TABLE IF NOT EXISTS `quest_lovers`.`booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_and_time_of_creation` DATETIME NOT NULL,
  `date_and_time` DATETIME NOT NULL,
  `price` INT NOT NULL,
  `status` TINYINT NOT NULL,
  `user_id` INT NOT NULL,
  `quest_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `quest_id`),
  INDEX `fk_booking_user_idx` (`user_id` ASC),
  INDEX `fk_booking_quest1_idx` (`quest_id` ASC),
  CONSTRAINT `fk_booking_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `quest_lovers`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_quest1`
    FOREIGN KEY (`quest_id`)
    REFERENCES `quest_lovers`.`quest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quest_lovers`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quest_lovers`.`genre` ;

CREATE TABLE IF NOT EXISTS `quest_lovers`.`genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quest_lovers`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quest_lovers`.`review` ;

CREATE TABLE IF NOT EXISTS `quest_lovers`.`review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rating` FLOAT NULL,
  `text` VARCHAR(200) NULL,
  `data_and_time` DATETIME NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_review_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_review_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `quest_lovers`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quest_lovers`.`review_has_quest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quest_lovers`.`review_has_quest` ;

CREATE TABLE IF NOT EXISTS `quest_lovers`.`review_has_quest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `review_id` INT NOT NULL,
  `review_user_id` INT NOT NULL,
  `quest_id` INT NOT NULL,
  PRIMARY KEY (`id`, `review_id`, `review_user_id`, `quest_id`),
  INDEX `fk_review_has_quest_quest1_idx` (`quest_id` ASC),
  INDEX `fk_review_has_quest_review1_idx` (`review_id` ASC, `review_user_id` ASC),
  CONSTRAINT `fk_review_has_quest_review1`
    FOREIGN KEY (`review_id` , `review_user_id`)
    REFERENCES `quest_lovers`.`review` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_has_quest_quest1`
    FOREIGN KEY (`quest_id`)
    REFERENCES `quest_lovers`.`quest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quest_lovers`.`quest_has_genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quest_lovers`.`quest_has_genre` ;

CREATE TABLE IF NOT EXISTS `quest_lovers`.`quest_has_genre` (
  `quest_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`quest_id`, `genre_id`),
  INDEX `fk_quest_has_genre_genre1_idx` (`genre_id` ASC),
  INDEX `fk_quest_has_genre_quest1_idx` (`quest_id` ASC),
  CONSTRAINT `fk_quest_has_genre_quest1`
    FOREIGN KEY (`quest_id`)
    REFERENCES `quest_lovers`.`quest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quest_has_genre_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `quest_lovers`.`genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
